const Responses = {
  SOCKET_SEND_MOVE: "sendMove",
  SOCKET_SEND_JOIN_GAME: "joinGame",
  SOCKET_UPDATE_GAME: "SOCKET_UPDATE_GAME",
  SOCKET_UPDATE_LEADERBOARD: "SOCKET_UPDATE_LEADERBOARD",
  APP_LOAD: "APP_LOAD",
  SOCKET_LOAD_PAST_GAMES: "SOCKET_LOAD_PAST_GAMES",
};

module.exports = Responses;
