export const SOCKET_UPDATE_GAME = "SOCKET_UPDATE_GAME";
export const SOCKET_UPDATE_LEADERBOARD = "SOCKET_UPDATE_LEADERBOARD";
export const APP_LOAD = "APP_LOAD";
export const SOCKET_LOAD_PAST_GAMES = "SOCKET_LOAD_PAST_GAMES";
